### PR TITLE
initial round of fixes for Team Helium

### PR DESCRIPTION
**Pull request by ctb**
- removed He from 2M.3.DEMO
- added He demo 4 to 3M.5.FULLSTACKS
- added He demo 8 to 5M1.DEMO
- added new He demo 12 to 5M3.DEMO ([see helium demo 12](https://dcppc-phase-1-demos.readthedocs.io/en/update-helium/descriptions/helium-demo12.html))
- added helium-demo12 to TOC after merge of #3

See new [demo descriptions index](https://dcppc-phase-1-demos.readthedocs.io/en/update-helium/descriptions/index.html)

### CODE REVIEW

**Comment by KCB13** [comment]
I have 2 more Helium demo descriptions to add for Team Helium that would be better added after this pull request goes through: 

2M.2 - Demonstrate interoperability of search with access controls across cloud environments

 

A user will be able to:
* Do a full text search that retrieves indexed documents via the search engine.
* ​Select a search result
* Navigate to the document found by the search
* For users authenticated to HeliumShare, authorization levels will apply in determining the user's ability to view the selected content.
* Non authenticated users will be prompted to authenticate to HeliumShare.
Note: This capability does not entail the sort of field level access control enabled by the ElasticSearch Shield plugin though that is being investigated for a future release.

​4M.2 - Portable workflow scheduled on two or more stacks using the same API
* A CWL workflow designed to be platform independent will be published to Dockstore.
* The workflow will be executed on the Helium stack.
* ​This step may be via the reference CWL runner, Toil, or a GA4GH WES endpoint.
* The workflow will be executed on another stack.
* This step will depend on the execution entrypoint of the other stack. 
* Outputs of each workflow will be verified as correct with respect to expected outcomes.

**Comment by ctb** [comment]
Hi @KCB13 this is now ready to be reviewed, if you can take a minute - thanks!

**Comment by ACharbonneau** [comment]
Hey. I found this when I was making projects...is it still a thing that needs to happen? Or should I just close it?

**Comment by ctb** [comment]
go ahead and close, I think.

**Pull request closed without merging**
